### ISSUE TITLE
Add brief bit on the structure of a bash command

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-shell-DEPRECATED#28]
Suggestions from Jamie @jamieviva that we add something on the general structure of bash. So, something like:

> COMMAND -FLAG FILE.USED

Then explain structure of what happens thereafter, so:

> if you add nothing = print to shell; if you add `> FILE.OUTPUT` = save to file; if you add '|' = save to memory for next command.

It probably should do somewhere in https://github.com/data-lessons/library-shell/blob/gh-pages/_episodes/01-intro-shell.md not before doing work in the shell, but as a "look at what you've also learned!" outcome.

Thoughts?

**Comment by weaverbel** [comment]
I might have a crack at this. It might be good to diagram it with call-out text on each segment as a picture is worth 1,000 ...

**Comment by jamieviva** [comment]
@weaverbel that's exactly what I envisioned - something like an 'anatomy of a DOI' or 'anatomy of URL diagram,' [maybe like this](https://lh4.googleusercontent.com/-Lx69aIsa078/TXuNzpIGRbI/AAAAAAAAACw/95JWAs_yYsw/s1600/URL.png)?

**Comment by weaverbel** [comment]
On it

**Comment by jduckles** [comment]
There is an opportunity in this diagram to point out that what we call a Command Line Environment or Shell is really just big words for saying you're stuck inside of an unending: Read / Evaluate / Print loop. 

The shell is waiting (VERY patiently) for you to type something (READ), it echoes that back to you and then when you finally sculpt the incantation the way you like, you hit <enter> (EVALUATE). Then it goes off and evaluates what you've typed and returns (or doesn't) text to the screen (PRINT).

**Comment by drjwbaker** [comment]
@jduckles This is a really good point. I stress the structure of commands and Read / Evaluate / Print (though not in those exact terms!) a lot.

**Comment by weaverbel** [comment]
Still haven't got to this - travel and then the sprint intervened. If anyone can have a crack, go for it, though I will eventually do it - just trying to do post-sprint tidy-up first.
