### ISSUE TITLE
Improve lesson objectives

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-shell-DEPRECATED#32]
Improve the lesson/learning objectives in the Overview box at the top of each episode e.g. http://data-lessons.github.io/library-shell/01-intro-shell/, http://data-lessons.github.io/library-shell/03-free-text/.

Please see Writing Learning Objectives http://swcarpentry.github.io/instructor-training/19-lessons/.

**Comment by drjwbaker** [comment]
Refer to https://github.com/data-lessons/library-shell/issues/29 when working on this.
