### ISSUE TITLE
Handout

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-shell-DEPRECATED#44]
Once workflow for building handouts at https://github.com/data-lessons/librarycarpentry/issues/30 is resolved, delete cheat sheet material from http://data-lessons.github.io/library-shell/reference/

**Comment by drjwbaker** [comment]
Oh, and fix 'Making a Handout' instructions at https://github.com/data-lessons/library-shell/blob/gh-pages/_extras/guide.md whilst you are there :)

**Comment by drjwbaker** [comment]
Maintainers @weaverbel @jt14den: I'm running a LC workhop in Padua with @danmichaelo in 14-15 September. They asked if we can get the handouts for the lessons in place so they can translate them for the workshop (they want to translate the handouts only, not the lessons!). This is one of the lessons we'll use. Any chance you could take a look and confirm it is good to go this week? (w/c 31 July) If not, could you give me a timescale I can pass on?

**Comment by weaverbel** [comment]
I actually created a manual handout for my Adelaide workshop - will email it to you @drjwbaker . Also the PRs have an x next to them - should I review and merge or not?

**Comment by weaverbel** [comment]
All the PRs that are outstanding fail the Travis CI build because of a missing .yaml. I have asked @rgaiacs as he might know what to do. I amended three of them myself because I thought it might be rogue formatting like smart quotes but it is the .yaml. I have been able to update files so it is something at @drjwbaker's end I think. Are you pushing from command line, or through Web?

**Comment by rgaiacs** [comment]
@weaverbel as I mentioned, the pull request is failing because you don't have a `.travis.yml` file. You need to create it or disable it. I don't know what are you trying to check with Travis.

**Comment by drjwbaker** [comment]
I don't know what Travis is :|

**Comment by rgaiacs** [comment]
https://travis-ci.org/ is a continuous integration service.

**Comment by weaverbel** [comment]
I have never had problems with a Travis CI build so I think it is something
on James's local Jekyll set up maybe?

Belinda Weaver
Community Development Lead
Software and Data Carpentry
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by drjwbaker** [comment]
Weird. Pretty sure I was just editing via GitHub..

**Comment by rgaiacs** [comment]
This is a configuration on GitHub Settings. You can go to Settings, Integration & Services to disable it.

![screencapture-github-rgaiacs-swc-workshop-template-settings-installations-1501838392129](https://user-images.githubusercontent.com/1506457/28962769-acebb3f8-78fe-11e7-84fd-721397e7c9be.png)

**Comment by drjwbaker** [comment]
Thanks @rgaiacs. Do you want to remove this maintainers?

**Comment by weaverbel** [comment]
Yes, let's get rid of it. Jekyll is finicky enough - let's not complicate things further.

**Comment by drjwbaker** [comment]
Done.

**Comment by drjwbaker** [comment]
So can we merge the PRs here despite the Travis failures?

**Comment by drjwbaker** [comment]
Just spotted that we just undid something we did in the sprint.. https://github.com/data-lessons/librarycarpentry/issues/38
