### ISSUE TITLE
LittleWomen example gives incorrect answers

### ISSUE THREAD

**Issue by gcapes** [data-lessons/library-shell-DEPRECATED#82]
See [Software Carpentry lesson ](https://swcarpentry.github.io/shell-novice/07-find/) for comparison.

**Comment by weaverbel** [comment]
What is the wrong with the example in this lesson? It always works for me in workshops @gcapes

**Comment by gcapes** [comment]
It gives the wrong answers ;) Compare against the linked example.
In the library example:
`grep $name littlewomen.txt | wc -w`
grep returns the lines containing a match to $name, and wc counts the number of words in those lines.
We want to count the number of times $name occurs. PR #83 does this.

**Comment by jcoliver** [comment]
Should be fixed by LibraryCarpentry/lc-shell#13.
